:startup_test:
- 'pi.http.viadns.org'
- '3.14.159.26'
:bind_address: '0.0.0.0'
:bind_port: 1053
:backend: 'http'
:base_url: 'http://www.domdori.com/dns/records/'
#:base_url: 'http://viadns.org/examples/'
# :driver: 'sqlite3'
# :path: 'dns.sqlite3'
:pid_file: 'pid/eventdns.pid'
:log_file: 'log/eventdns.log'
:log_level: :debug